GymMgmtSys/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/',include('django.contrib.auth.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from app import views
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HOME, name='home'),
    path('base/', views.BASE, name='base'),
    path('pricing/', views.PRICING, name='pricing'),
    path('faq', views.FAQ, name='faq'),
    path('enquiry', views.ENQUIRY, name='enquiry'),
    path('pagedetail/<int:id>', views.page_detail, name='pagedetail'),


    path('gallery', views.gallery, name='gallery'),
    path('gallery_detail/<int:id>', views.gallery_detail, name='gallery_detail'),
    path('accounts/', include('django.contrib.auth.urls')),

    path('login', views.DO_LOGIN, name='login'),
    path('404', views.Error404, name='404'),
    path('accounts/signup',views.signup,name='signup' ),
    path('checkout/<int:plan_id>',views.CHECKOUT,name='checkout'),
    #path('checkout_session/<int:plan_id>',views.checkout_session(),name='checkout_session'),
    path('pay_success',views.pay_success,name='pay_success'),
    path('pay_cancel', views.pay_cancel, name='pay_cancel'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
# Create your models here.
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User

#Banners
class Banners(models.Model):
    img = models.ImageField(upload_to="banners/")
    alt_text = models.CharField(max_length=150)
    def __str__(self):
        return self.alt_text

    def image_tag(self):
        return mark_safe('<img src= "%s"  width="80" />' %(self.img.url))


# Create your models here.
class Service(models.Model):
    title = models.CharField(max_length=150)
    detail = models.TextField()
    img = models.ImageField(upload_to="services/", null=True)

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src= "%s"  width="80" />' % (self.img.url))

#Pages
class Page(models.Model):
    title = models.CharField(max_length=150)
    detail = models.TextField()
    def __str__(self):
        return self.title

#FAQ
class Faq(models.Model):
    Ques = models.TextField(max_length=150)
    Ans = models.TextField()
    def __str__(self):
        return self.Ques


#Enquiry
class Enquiry(models.Model):
    full_Name=models.CharField(max_length=200)
    email = models.EmailField()
    message =models.TextField()
    send_time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_Name

#Gallery
class Gallery(models.Model):
    title=models.CharField(max_length=100)
    detail=models.TextField()
    img = models.ImageField(upload_to="gallery/", null=True)

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src= "%s"  width="80" />' % (self.img.url))

#Gallery Images
class GalleryImage(models.Model):
    gallery=models.ForeignKey(Gallery,on_delete=models.CASCADE,null=True)
    alt_text=models.CharField(max_length=100)

    img = models.ImageField(upload_to="gallery_imgs/", null=True)

    def __str__(self):
        return self.alt_text

    def image_tag(self):
        return mark_safe('<img src= "%s"  width="80" />' % (self.img.url))

#Subcription Plans
class SubPlan(models.Model):
    title = models.CharField(max_length=200)
    price = models.IntegerField()
    max_member=models.IntegerField(null=True)
    highlights_status =models.BooleanField(default=False,null=True)
    def __str__(self):
        return self.title

#Subcription Plans Features
class SubPlanFeature(models.Model):

   #subplan=models.ForeignKey(SubPlan,on_delete=models.CASCADE,null=True)
   subplan = models.ManyToManyField(SubPlan)
   title = models.CharField(max_length=50)

   def __str__(self):
       return self.title
#Package discount
class PlanDiscount(models.Model):
    #subplan=models.ForeignKey(SubPlan,on_delete=models.CASCADE)
    subplan = models.ManyToManyField(SubPlan)
    total_months=models.IntegerField()
    total_discount=models.IntegerField()

    def __str__(self):
        return str(self.total_months)

#Subscriber
class subscriber(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    phone_number=models.CharField(max_length=15)
    address=models.CharField(max_length=100)
    img=models.ImageField(upload_to="subs/")

    def __str__(self):
        return self.subs

    def image_tag(self):
        return mark_safe('<img src= "%s"  width="80" />' % (self.img.url))
#Subcription
class subcription(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    plan = models.ForeignKey(SubPlan, on_delete=models.CASCADE, null=True)
    price=models.IntegerField()

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet" />
    <!-- Bootstrap Icons -->
    <link href="{% static 'bootstrap-icons/font/bootstrap-icons.css' %}" rel="stylesheet" />
    <!-- Include jquery -->
    <script type="text/javascript" src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <title>Home - Arnold GYM</title>
  </head>
  <body>
    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light bg-warning">
	  <div class="container">
	    <a class="navbar-brand" href="/">Arnold GYM</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarNav">
	      <ul class="navbar-nav ms-auto">
	        <li class="nav-item">
	          <a class="nav-link" aria-current="page" href="/">Home</a>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link" aria-current="page" href="{% url 'gallery' %}">Gallery</a>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link" href="{% url 'pricing' %}">Pricing</a>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link " href="{% url 'enquiry' %}">Enquiry</a>
	        </li>
	        <li class="nav-item dropdown">
	          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
	            My Account
	          </a>
	          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
				  {% if  not user.is_authenticated %}
				  <li><a class="dropdown-item" href="{% url 'signup' %}">Register</a></li>
	            <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
				  <li><a class="dropdown-item" href="#">Settings</a></li>
				  {% else %}
				  <li><a class="dropdown-item">{{user.username}}</a></li>
	            <li><a class="dropdown-item" href="#">Profile</a></li>

	            <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
				  {% endif %}
	          </ul>
	        </li>
	      </ul>
	    </div>
	  </div>
	</nav>
    <!-- Header End -->
{% block content %}


{% endblock %}

   <!-- Footer Start -->
  <footer class="container py-5">
	    <p class="float-end"><a href="#">Back to top</a></p>
	    <p>© 2017–2021 Arnold GYM, Inc. ·
            <a href="{% url 'pagedetail' 2 %}">Privacy</a> ·
            <a href="{% url 'pagedetail' 3 %}">Terms</a> .
            <a href="{% url 'faq' %}">FAQ</a> .
			<a href="{% url '404' %}">Contact Us</a> .
        </p>
	  </footer>


<!-- Bootstrap Bundle -->
<script src="{% static 'bootstrap.bundle.min.js' %}"></script>
<script type="text/javascript" src="{% static 'popper.min.js' %}"></script>
</body>
</html>

templates/cancel.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h3> Sorry!! Your payment is cancelled.</h3>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">Checkout</h1>
				<table class="table table-bordered">
					<thead class="table-warning">
						<tr>
							<th>Plan</th>
							<th>Plan Detail</th>
							<th>Payment For</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								<table class="table-bordered table">
									<tr>
										<th>Name</th>
										<td>{{plan.title}}</td>
									</tr>
									<tr>
										<th>Price</th>
										<td>${{plan.price}}</td>
									</tr>
									<tr>
										<th>Max Member</th>
										<td>{{plan.max_member}}</td>
									</tr>
									<tr>
										<th>Already Registered</th>
										<td>15</td>
									</tr>
									<tr>
										<th>Remaining Seats</th>
										<td>15</td>
									</tr>
								</table>
							</td>
							<td>
								<ul class="list-unstyled">
									{% for feature in plan.subplanfeature_set.all %}
					              <li>{{feature.title}}</li>
									{% endfor %}

					            </ul>
							</td>
							<td>
								<table class="table table-bordered">
									{% for discount in plan.plandiscount_set.all %}



									<tr>
										<td><input data-planprice="{{plan.price}}" data-discount="{{discount.total_discount}}" type="radio" id="validity{{discount.id}}" name="validity" class="select-validity" value="{{discount.total_months}}" /></td>
										<th><label for="{{discount.total_discount}}">{{discount.total_months}} Month</label></th>
										<td> {{discount.total_discount}}%</td>
									</tr>
									{% endfor %}


								</table>
							</td>
						</tr>
					</tbody>
					<tfoot class="table-info">
						<tr>
							<td></td>
							<th>Total Amount</th>
							<td><b>$<span class="totalAmount">{{plan.price}}</span></b></td>
						</tr>
						<tr>
							<td colspan="2"></td>
							<td>
								<form method="post" action="{% url 'checkout_session'  %}">
									{% csrf_token %}
								<input type="submit" value="Proceed to Payment" class="btn btn-primary" />
								</form>
							</td>
						</tr>
					</tfoot>
				</table>
		</section>
		<!-- End -->
    </main>
    <!-- End -->

<script type="text/javascript">
	$(document).ready(function(){
		$(".select-validity").on('click',function(){
			var _planPrice=$(this).attr('data-planprice');
			var _planDisc=$(this).attr('data-discount');
			var _planValid=$(this).val();
			var _totalPrice=_planPrice*_planValid;
			if(_planDisc>0){
				var _discountedPrice=_totalPrice*_planDisc/100;
				_discountedPrice=_totalPrice-_discountedPrice;
			}else{
				var _discountedPrice=_totalPrice;
			}
			$(".totalAmount").text(_discountedPrice);
		});
	});
</script>
{% endblock %}

templates/enquiry.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">Enquiry Form</h1>
			<div class="row">
				<div class="col-md-6">
					<img src="{% static 'imgs/enquiry.jpg' %}" class="img-fluid" />
				</div>
				<div class="col-md-6">
					{% if msg %}
					<p class="text-success">{{msg}}</p>
					{% endif %}
					<form method="post" action=" {% url 'enquiry' %}">
						{% csrf_token %}
						<table class="table table-bordered">
							{{form.as_table}}
							<tr>
								<td colspan="2">
									<input type="submit" class="btn btn-primary" />
								</td>
							</tr>
						</table>
					</form>
				</div>
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

templates/faq.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">FAQ</h1>
			<div class="accordion" id="accordionExample">
				{% for faq in faqs %}
			  <div class="accordion-item">
			    <h2 class="accordion-header" id="headingOne">
			      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne{{forloop.counter}}" aria-expanded="true" aria-controls="collapseOne">
			      {{faq.Ques}}
			      </button>
			    </h2>
			    <div id="collapseOne{{forloop.counter}}" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
			      <div class="accordion-body">
			       {{faq.Ans}}
			      </div>
			    </div>
			  </div>
				{% endfor %}


			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

templates/gallery.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">Gallery</h1>
			<div class="row">
				{% for gallery in gallerys %}
				<div class="col-md-4 mb-4">
					<div class="card">
					  <img src="{{gallery.img.url}}" class="card-img-top" alt="{{gallery.title">
					  <div class="card-body">
					    <h5 class="card-title">{{gallery.title}}</h5>
					    <p class="card-text">{{gallery.detail}}</p>
					    <a href="{% url 'gallery_detail' gallery.id %}" class="btn btn-primary">View All</a>
					  </div>
					</div>
				</div>
				{% endfor %}

			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

templates/gallery_imgs.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">{{gallery.title}} Image</h1>
			<div class="row">
				{% for gimg in gallery_imgs %}
				<div class="col-md-4 mb-4">
					<div class="card">
					  <img src="{{gimg.img.url}}" class="card-img-top" alt="{{gimg.alt_text}}">

					</div>
				</div>
				{% endfor %}

			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Main Start -->
    <main>
    	<!-- banner Start -->
    	<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
		  <div class="carousel-inner">
			  {% for banner in banners %}
		    <div class="carousel-item {% if forloop.counter == 1%} active {% endif %}">
		      <img src="{{banner.img.url}}" class="d-block w-100" alt="Slide 1">
		    </div>
			  {% endfor %}

		  </div>
		  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
		    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
		    <span class="visually-hidden">Previous</span>
		  </button>
		  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
		    <span class="carousel-control-next-icon" aria-hidden="true"></span>
		    <span class="visually-hidden">Next</span>
		  </button>
		</div>
		<!-- End Banner -->
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading">Services</h1>
			<div class="row">
				{% for service in services %}
				<div class="col-md-4">
					<div class="card">
					  <img src="{{service.img.url}}" class="card-img-top" alt="...">
					  <div class="card-body">
					    <h3 class="card-title">{{service.title}}</h3>
					    <p class="card-text">{{service.detail|truncatewords:9}}</p>
					    <a href="#" class="btn btn-primary">Read More</a>

					  </div>

					</div>
				</div>
				{% endfor %}


			</div>
		</section>
		<!-- End -->

		<!-- Testimonials -->
		<section class="container-fluid bg-light py-4 mt-5 border-top border-bottom">
			<div class="container">
				<div class="row">
					<div class="col-md-5">
							<h1 class="mb-4 section-heading">About Us</h1>
							<p class="lh-base">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1550s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
							<p><a href="{% url 'pagedetail' 1 %}" class="btn btn-info text-white">Read More</a></p>
					</div>
					<div class="col-md-6 offset-1">
							<h1 class="mb-4 section-heading">Gallery <a href="#" class="float-end btn btn-info text-white mt-2">View All</a></h1>
							<div class="gallery">
								<a data-lightbox="home-gallery" href="imgs/body-2.jpg"><img src="imgs/body-2.jpg" width="155" class="img-thumbnail" alt="..."></a>
								<a data-lightbox="home-gallery" href="imgs/body-2.jpg"><img src="imgs/body-2.jpg" width="155" class="img-thumbnail" alt="..."></a>
								<a data-lightbox="home-gallery" href="imgs/body-2.jpg"><img src="imgs/cardio-1.jpg" width="155" class="img-thumbnail" alt="..."></a>
								<a data-lightbox="home-gallery" href="imgs/body-2.jpg"><img src="imgs/body-2.jpg" width="155" class="img-thumbnail" alt="..."></a>
								<a data-lightbox="home-gallery" href="imgs/body-2.jpg"><img src="imgs/cardio-1.jpg" width="155" class="img-thumbnail" alt="..."></a>
								<a data-lightbox="home-gallery" href="imgs/body-2.jpg"><img src="imgs/body-2.jpg" width="155" class="img-thumbnail" alt="..."></a>
								<a data-lightbox="home-gallery" href="imgs/body-2.jpg"><img src="imgs/body-2.jpg" width="155" class="img-thumbnail" alt="..."></a>
								<a data-lightbox="home-gallery" href="imgs/body-2.jpg"><img src="imgs/cardio-1.jpg" width="155" class="img-thumbnail" alt="..."></a>
								<a data-lightbox="home-gallery" href="imgs/body-2.jpg"><img src="imgs/body-2.jpg" width="155" class="img-thumbnail" alt="..."></a>
								<a data-lightbox="home-gallery" href="imgs/body-2.jpg"><img src="imgs/dance-3.jpg" width="155" class="img-thumbnail" alt="..."></a>
								<a data-lightbox="home-gallery" href="imgs/body-2.jpg"><img src="imgs/body-2.jpg" width="155" class="img-thumbnail" alt="..."></a>
								<a data-lightbox="home-gallery" href="imgs/body-2.jpg"><img src="imgs/body-2.jpg" width="155" class="img-thumbnail" alt="..."></a>
							</div>
					</div>
				</div>
			</div>
		</section>
		<!-- End Testimonials -->

    </main>
    <!-- End -->

<script type="text/javascript" src="{% static 'lightbox2-2.11.3/dist/js/lightbox.min.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'lightbox2-2.11.3/dist/css/lightbox.min.css' %}" />

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">Login</h1>
			<div class="row">
				<div class="col-md-6 offset-3">
					<form>
						<table class="table table-bordered">
							<tr>
								<th>Username <span class="text-danger">*</span></th>
								<td><input type="text" class="form-control" placeholder="Full Name" /></td>
							</tr>
							<tr>
								<th>Password <span class="text-danger">*</span></th>
								<td><input type="password" class="form-control" placeholder="Email" /></td>
							</tr>
							<tr>
								<td colspan="2">
									<input type="submit" class="btn btn-primary" />
								</td>
							</tr>
						</table>
					</form>
				</div>
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

templates/page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">{{page.title}}</h1>
			<p> {{page.detail}}</p>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

templates/pricing.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!-- Main Start -->
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-icons/font/bootstrap-icons.css' %}" />
    <section class="container my-4">
    	<h1 class="text-center mb-4 section-heading border-bottom pb-2">Plans</h1>
  <main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
      {% for plan in plans %}
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm  {% if plan.highlights_status %} border-primary {% endif %}">
          {% if plan.highlights_status %}
          <div class="card-header py-3 text-white bg-primary border-primary">
            {% else %}
          <div class="card-header py-3">
            {% endif %}
            <h4 class="my-0 fw-normal">{{plan.title}}</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">${{plan.price}}<small class="text-muted fw-light">/mo</small></h1>
            <p class="text-success">Member Capacity ={{plan.max_member}}</p>
            <ul  class="list-unstyled mt-3 mb-4">
              {% for feature in plan.subplanfeature_set.all %}
              <li>{{feature.title}}</li>
              {% endfor %}

            </ul>
            {% if request.user.is_authenticated %}
            <a  class="w-100 btn btn-lg btn-outline-primary" href="{% url 'checkout' plan.id %}">Get started</a>
            {% else %}

             <a  class="w-100 btn btn-lg btn-outline-primary" href="{% url 'login' %}">  Get started</a>



            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}

    </div>

    <h2 class="display-6 text-center mb-4">Compare plans</h2>

    <div class="table-responsive">
      <table class="table text-center">
        <thead>
          <tr>
            <th style="width: 34%;"></th>
            {% for plan in plans %}
            <th style="width: 22%;">{{plan.title}}</th>
        {% endfor %}

        </thead>
        <tbody>
         {% for f in dfeatures %}
          <tr>

            <th scope="row" class="text-start">{{f.title}}</th>
             {% for plan in plans %}
            <td>
              {% if plan in f.subplan.all %}
              <i class="bi bi-check-lg"></i></td>
            {% else %}
             <i class="bi bi-x-lg text-danger"></i>
            {% endif %}
            </td>
              {% endfor %}
          </tr>
   {% endfor %}


        </tbody>
      </table>
    </div>
  </main>
</section>
    <!-- End -->

{% endblock %}

templates/service.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">Cardio Service</h1>
			<p>
				<img src="imgs/23.jpg" class="img-fluid border-secondary border" />
			</p>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
			<ul class="list-group mt-4">
			  <li class="list-group-item">An item</li>
			  <li class="list-group-item">A second item</li>
			  <li class="list-group-item">A third item</li>
			  <li class="list-group-item">A fourth item</li>
			  <li class="list-group-item">And a fifth one</li>
			</ul>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

templates/success.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h3> Thanks for Payment</h3>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}